# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hellogrpc/hellogrpc/hellogrpc.proto for package 'hellogrpc'

require 'grpc'
require './proto/hellogrpc_pb'

module Hellogrpc
  module Greeter
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'hellogrpc.Greeter'

      rpc :SayHello, ::Hellogrpc::HelloRequest, ::Hellogrpc::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end

